### PR TITLE
Transform references to Rc + RefCell in order to eliminate self-refer…

### PR DESCRIPTION
**Pull request by sheosi**
I've been working with TtsPico in one project, and I wanted to have everything inside one struct, however that meant either using not so elegant parts of the API or reworking this library to use Rc and RefCell, since that would make sense for a lot of use cases, this is what I've done

### CODE REVIEW

**Comment by UberLambda** [comment]
Looks good! This is my first project in Rust (as a C++ guy) so I'm still a bit fuzzy about what's good practice, but I can see why this change was needed :)

I'm bumping up the version number, adding copyright info and merging.

**Comment by UberLambda** [comment]
@sheosi Do you want added to the copyright with your real name or do I just put "and contributors" or similar?

**Comment by sheosi** [comment]
> Looks good! This is my first project in Rust (as a C++ guy) so I'm still a bit fuzzy about what's good practice, but I can see why this change was needed :)
> 
> I'm bumping up the version number, adding copyright info and merging.
Pretty much the same here, I've worked with other languages but the project make the first time I've worked with Rust, honestly got to this thanks to some guys on the rust subreddit.

> @sheosi Do you want added to the copyright with your real name or do I just put "and contributors" or similar?

The copyright with my name would be sweet ^^, also it's pretty nice to have this done.

**Comment by UberLambda** [comment]
Merged, cheers!

**Pull request merged**
